dataset: nyu
phase: eval
batch_size: 1
gpus: [0]
log_dir: ./logs/nyu/eval_25select9
pre_model_name: ./checkpoint/nyu/25select9.pth
level: 4
n_head: 1
d_attn: 256
d_k: 64
d_v: 64
d_inner: 256
num_select: 9
num_worker: 5
save_result: True