dataset: nyu
phase: train
split: 5
batch_size: 10
num_epoch: 50
gpus: [0]
learning_rate: 0.0005
model_saved_path: ./checkpoint/nyu/train_25select15
log_dir: ./logs/nyu/train_25select15
learning_decay_rate: 0.95
reg_weight: 1e-6
level: 4
n_head: 1
d_attn: 256
d_k: 64
d_v: 64
d_inner: 256
dropout_rate: 0.5
num_select: 15
num_worker: 5
max_jitter: 0.
offset: 20.
depth_sigma: 0.
random_flip: False
adjust_cube: False