dataset: nyu
phase: train
split: 5
batch_size: 32
num_epoch: 30
gpus: [0]
learning_rate: 0.0005
model_saved_path: ./checkpoint/nyu/train_25select3_light
log_dir: ./logs/nyu/train_25select3_light
pre_a2j: ./checkpoint/nyu/train_25select3/model.pth
learning_decay_rate: 0.95
reg_weight: 1e-6
level: 4
n_head: 1
d_attn: 256
d_k: 64
d_v: 64
d_inner: 256
dropout_rate: 0.5
num_select: 3
num_worker: 4
max_jitter: 0.
offset: 20.
depth_sigma: 0.
random_flip: False
adjust_cube: False