phase: eval
dataset: icvl
batch_size: 1
gpus: [0]
log_dir: ./logs/icvl/eval_uniform3
pre_model_name: ./checkpoint/icvl/uniform.pth
level: 1
n_head: 1
d_attn: 256
d_k: 64
d_v: 64
d_inner: 256
num_select: 3
num_worker: 5
save_result: True