dataset: icvl
phase: eval
batch_size: 1
gpus: [0]
log_dir: ./logs/icvl/eval_25select1_light
pre_a2j: ./checkpoint/icvl/25select3.pth
pre_model_path: ./checkpoint/icvl/25select3_light.pth
level: 4
n_head: 1
d_attn: 256
d_k: 64
d_v: 64
d_inner: 256
num_select: 1
num_worker: 8
save_result: True