dataset: icvl
phase: train
split: 20
batch_size: 32
num_epoch: 10
gpus: [0]
learning_rate: 0.0005
model_saved_path: ./checkpoint/icvl/train_25select9_light
log_dir: ./logs/icvl/train_25select9_light
pre_a2j: ./checkpoint/icvl/train_25select9/model.pth
learning_decay_rate: 0.8
reg_weight: 1e-6
level: 4
n_head: 1
d_attn: 256
d_k: 64
d_v: 64
d_inner: 256
dropout_rate: 0.5
num_select: 9
num_worker: 8
max_jitter: 0.
depth_sigma: 0.
random_flip: False
adjust_cube: False