phase: train
dataset: icvl
split: 20
batch_size: 10
num_epoch: 60
gpus: [0]
learning_rate: 0.0005
model_saved_path: ./checkpoint/icvl/train_uniform
log_dir: ./logs/icvl/train_uniform
learning_decay_rate: 0.95
reg_weight: 1e-6
level: 4
n_head: 1
d_attn: 256
d_k: 64
d_v: 64
d_inner: 256
dropout_rate: 0.5
num_select: 25
num_worker: 5
max_jitter: 0.
depth_sigma: 0.
random_flip: False
adjust_cube: False